<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit47e9e238c2a7fa88a014799a0fe35e70
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit47e9e238c2a7fa88a014799a0fe35e70::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit47e9e238c2a7fa88a014799a0fe35e70::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit47e9e238c2a7fa88a014799a0fe35e70::$classMap;

        }, null, ClassLoader::class);
    }
}
